# Generated by Django 4.1 on 2022-08-08 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('numEspecialistas', models.IntegerField()),
                ('totalSueldos', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25, null=True)),
                ('apellido', models.CharField(max_length=25, null=True)),
                ('cedula', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(max_length=30)),
                ('provincia', models.CharField(max_length=30)),
                ('callePrincipal', models.CharField(max_length=30)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ubicacion_list', to='administracionHospital.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracionHospital.persona')),
                ('edad', models.IntegerField()),
                ('peso', models.FloatField()),
                ('estatura', models.FloatField()),
                ('fechaNacimiento', models.DateField(verbose_name='Fecha')),
                ('genero', models.CharField(max_length=15)),
                ('motivo', models.CharField(help_text='Ingrese el motivo de ingreso', max_length=100)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paciente_list', to='administracionHospital.hospital')),
            ],
            bases=('administracionHospital.persona',),
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracionHospital.persona')),
                ('especialidad', models.CharField(max_length=30)),
                ('sueldo', models.FloatField()),
                ('numConsultorio', models.CharField(max_length=2)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medico_list', to='administracionHospital.hospital')),
            ],
            bases=('administracionHospital.persona',),
        ),
        migrations.CreateModel(
            name='Enfermero',
            fields=[
                ('persona_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracionHospital.persona')),
                ('sueldo', models.FloatField()),
                ('tipoContrato', models.CharField(max_length=40)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enfermero_list', to='administracionHospital.hospital')),
            ],
            bases=('administracionHospital.persona',),
        ),
    ]
