# Generated by Django 4.1 on 2022-08-08 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0002_paciente_medico_m'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='medico_m',
            new_name='medico_asignado',
        ),
    ]
