# Generated by Django 4.1 on 2022-08-08 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0004_paciente_enfermero_asignado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enfermero',
            old_name='tipoContrato',
            new_name='tipo_contrato',
        ),
        migrations.RenameField(
            model_name='hospital',
            old_name='totalSueldos',
            new_name='total_sueldos',
        ),
        migrations.RenameField(
            model_name='medico',
            old_name='numConsultorio',
            new_name='num_consultorio',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='fechaNacimiento',
            new_name='fecha_nacimiento',
        ),
        migrations.RenameField(
            model_name='ubicacion',
            old_name='callePrincipal',
            new_name='calle_principal',
        ),
        migrations.AddField(
            model_name='hospital',
            name='medico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_list', to='administracionHospital.medico'),
        ),
    ]
