# Generated by Django 4.1 on 2022-08-08 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0005_rename_tipocontrato_enfermero_tipo_contrato_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='numEspecialistas',
        ),
    ]
