# Generated by Django 4.1 on 2022-08-08 02:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0006_remove_hospital_numespecialistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='medico',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_list', to='administracionHospital.medico'),
        ),
    ]
