# Generated by Django 4.1 on 2022-08-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0008_remove_hospital_medico_alter_medico_num_consultorio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='edad',
            field=models.PositiveIntegerField(),
        ),
    ]
