# Generated by Django 4.1 on 2022-08-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0009_alter_paciente_edad'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='total_sueldos',
            field=models.FloatField(null=True),
        ),
    ]
