# Generated by Django 4.1 on 2022-08-09 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0010_medico_total_sueldos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='total_sueldos',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
