# Generated by Django 4.1 on 2022-08-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0011_alter_medico_total_sueldos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medico',
            name='total_sueldos',
        ),
    ]
