# Generated by Django 4.1 on 2022-08-09 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0012_remove_medico_total_sueldos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hospital',
            old_name='total_sueldos',
            new_name='total_sueldos_medicos',
        ),
    ]
