# Generated by Django 4.1 on 2022-08-09 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0013_rename_total_sueldos_hospital_total_sueldos_medicos'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='total_sueldos_enfermeros',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
