# Generated by Django 4.1 on 2022-08-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0017_alter_hospital_total_sueldos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='total_sueldos',
        ),
    ]
