# Generated by Django 4.1 on 2022-08-10 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0020_alter_hospital_total_sueldos'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='num_especialistas',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_sueldos',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_sueldos_enfermeros',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_sueldos_medicos',
            field=models.FloatField(null=True),
        ),
    ]
