# Generated by Django 4.1 on 2022-08-10 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0021_hospital_num_especialistas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='num_especialistas',
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_sueldos',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_sueldos_enfermeros',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='total_sueldos_medicos',
            field=models.FloatField(default=0, null=True),
        ),
    ]
