# Generated by Django 4.1 on 2022-08-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0022_alter_hospital_num_especialistas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='total_sueldos',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total_sueldos_enfermeros',
        ),
        migrations.RemoveField(
            model_name='hospital',
            name='total_sueldos_medicos',
        ),
        migrations.AlterField(
            model_name='hospital',
            name='num_especialistas',
            field=models.PositiveIntegerField(default=0, editable=False, null=True),
        ),
    ]
