# Generated by Django 4.1 on 2022-08-10 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0023_remove_hospital_total_sueldos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='num_especialistas',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
