# Generated by Django 4.1 on 2022-08-11 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0024_alter_hospital_num_especialistas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubicacion',
            name='hospital',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracionHospital.hospital'),
        ),
    ]
