# Generated by Django 4.1 on 2022-08-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0025_alter_ubicacion_hospital'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='motivo',
            field=models.TextField(help_text='Ingrese el motivo de ingreso'),
        ),
    ]
