# Generated by Django 4.1 on 2022-08-13 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0027_alter_paciente_enfermero_asignado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='fecha_nacimiento',
            new_name='fecha_ingreso',
        ),
    ]
