# Generated by Django 4.1 on 2022-08-14 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracionHospital', '0028_rename_fecha_nacimiento_paciente_fecha_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='motivo',
            field=models.TextField(),
        ),
    ]
